spring:
  datasource:
    url: jdbc:h2:mem:infodb
    driverClassName: org.h2.Driver
    username: scdemo
    password: scdemopass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-infodb
      settings:
        trace: false
logging:
  file: logs\book-added-info-service.log