spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: book-catalog-service
        uri: lb://BOOK-CATALOG-SERVICE
        predicates:
        - Path=/catalog/**
logging:
  file: logs\edge-gateway.log