spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          search-paths: '{application}'
server:
  port: 8888
logging:
  file: logs\config-server.log
  level:
    blog.panditmandar.scdemo.infra.configserver: DEBUG