spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/get2mandar/spring-cloud-demo.git
          username: get2mandar
          default-label: repo-based-config
          search-paths:
          - configstore/{application}
server:
  port: 8888
logging:
  file: logs\config-server.log
  level:
    blog.panditmandar.scdemo.infra.configserver: DEBUG