spring:
  datasource:
    url: jdbc:h2:mem:bookdb
    driverClassName: org.h2.Driver
    username: scdemo
    password: scdemopass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
#server:
#  servlet:
#    contextPath: /book-api
logging:
  file: logs\book-data-service.log